CREATE TABLE RECHARGES(
  MSISDN VARCHAR(14) PRIMARY KEY,
  RECHARGE_VALUE NUMBER NOT NULL,
  COUNTER SMALLINT(1) NOT NULL,
  STATUS VARCHAR (20) NOT NULL
);

CREATE TABLE GIFTS(
  GIFT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  GIFT_VALUE NUMBER NOT NULL ,
  GIFT_PRICE NUMBER,
  RECHARGE_ID VARCHAR(14) NOT NULL
);

ALTER TABLE GIFTS ADD FOREIGN KEY (RECHARGE_ID) REFERENCES RECHARGES(MSISDN);

